### ISSUE TITLE
Database download problem

### ISSUE THREAD

**Issue by gdarko** [gdarko/ip-location-block#2]
> The database download still doesn’t work after that, but I was able to move the database into the expected location manually. The “Settings” page still can’t see the database I put there, but if I try to look up my own IP address, it does work. 

Reported [here](https://wordpress.org/support/topic/fatal-error-undefined-function-wp_create_nonce/#post-15647471)

**Comment by ph00lt0** [comment]
Experiencing same issues as you reported, unfortunately it seems that the blocking also stays active after de-installation of the plugin.

**Comment by ddur** [comment]
wp_create_nonce is mentioned here:
https://github.com/gdarko/ip-location-block/blob/master/classes/class-ip-location-block-util.php#L533

**Comment by ddur** [comment]
@gdarko 

Latest commit is an year old. Do you still maintain this repository?

**Comment by gdarko** [comment]
Hey @ddur - Yes, sure. I still maintain this. I am focusing on a new update those days that provides some improvements with the latest PHP 8.2 but interested to fix any other bug that is still there.

**Comment by ddur** [comment]
Just today I found out about your plugin. I will revive my extension as soon as I can.

**Comment by ddur** [comment]
@gdarko 

> > The database download still doesn’t work after that, but I was able to move the database into the expected location manually. The “Settings” page still can’t see the database I put there, but if I try to look up my own IP address, it does work.
> 
> Reported [here](https://wordpress.org/support/topic/fatal-error-undefined-function-wp_create_nonce/#post-15647471)

What/which database is he talking about?

**Comment by gdarko** [comment]
Hey @ddur  - I think the local databases GeoLite2/IP2Location download. On some environments it failed, but so far i was not able to reproduce the issue.

**Comment by ddur** [comment]
Actually, it could be anything, OS, Server configuration, PHP configuration or conflict with another plugin.

It could be missing or invalid license?

Trying to solve this issue without user information and cooperation is waste of time.

I would close this conversation until someone with a problem can provide information about environment and plugins which would make possible to recreate environment and reproduce the issue.

What you think?

**Comment by gdarko** [comment]
Hey @ddur - I 100% agree on this, can be closed.
