### ISSUE TITLE
Deprecated: Passing null to parameter

### ISSUE THREAD

**Issue by sabbirsam** [gdarko/ip-location-block#4]
Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in C:\wamp64\www\wpxpertise\notifier\wp-content\plugins\ip-location-block\classes\class-ip-location-block-util.php on line 1383

Error link : [view](https://prnt.sc/BRePCSJjjjHb)

**Comment by gdarko** [comment]
Fixed
